# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d3e7f4953e8649cd384a5f3d72addc717c1b5012e449b3ce2abd12737ae5a5c3a980068914db622655ed2d9f437fef77215d443a07b728ea358e177557dc2366

test:
  secret_key_base: e7ef66bd683a7185659ed69bf1d1c749aef448270db71ec11e1c84ea3ef6b784ed526a098d8a3d5a10fcb68ee4b91b9811eb5b7ab27327f059dee09134e51ed5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
